<?php
return [
    'forums_dlc' => [
        'forums' => 'Forums',
        'board' => 'Tableau',
        'create' => 'Créer',
        'post' => 'Message',
        'posts' => 'Messages',
        'thread' => 'Fil de Discussion',
        'threads' => 'Fils de Discussions',
        'reply' => 'Réponse',
        'replies' => 'Répond à',
        'member' => 'Membre',
        'members' => 'Membres',
        'no_recent_posts' => 'Pas de Post récent',
        'forum_statistics' => 'Statistiques du Forum',
        'latest_posts' => 'Derniers Messages',
        'create_new_thread' => 'Crée un nouveau fil de Discussion',
        'thread_topic' => 'Titre du Sujet',
        'edit_topic' => 'Modifier un Sujet',
        'topic_required' => 'Un Titre est Requis !',
        'post_thread' => 'Poster',
        'post_reply' => 'Poster une Réponse',
        'post_changes' => 'Appliquer les Modifications',
        'cancel_editing' => 'Annulé les Modifications',
        'quote' => 'Citer',
        'edit' => 'Modifier',
        'move_thread' => 'Déplacer un Sujet',
        'lock_thread' => 'Vérrouiller le Sujet',
        'unlock_thread' => 'Déverrouiller le Sujet',
        'pin_thread' => 'Épingler le Sujet',
        'unpin_thread' => 'Désépingler le Sujet',
        'delete' => 'Supprimé',
        'thread_has_been_locked' => 'Ce Sujet à été Verrouiller',
        'sign_in_to_reply' => 'Se connecter pour répondre',
        'total_posts' => 'Total des Messages',
        'posts_per_day' => 'Messages par Jour',
        'quoted_notification' => '%s vous a cité dans un Message',
        'mentioned_notification' => '%s vous a mentionné dans un Message',
        'search' => 'Rechercher',
        'search_options' => 'Options de recherche',
        'forum_search_placeholder' => 'Rechercher par Sujet, Publication ou Nom d'Auteur',
        'no_results' => 'Aucun Résultats'
    ]
];
